### ISSUE TITLE
Add `ws_stream_wasm` to tlsnotary

### ISSUE THREAD

**Issue by 0xtsukino** [tlsnotary/tlsn-js#1]

**Comment by mhchia** [comment]
Would it work if I just transfer [this repo](https://github.com/mhchia/ws_stream_wasm) to tlsnotary organization?

**Comment by heeckhau** [comment]
@mhchia yes please! 🙏

**Comment by mhchia** [comment]
@heeckhau Already transferred: https://github.com/tlsnotary/ws_stream_wasm 🙏
