### ISSUE TITLE
Error: prover error: io error caused by: not connected

### ISSUE THREAD

**Issue by tx-tomcat** [tlsnotary/tlsn-js#72]
Im using tlsn-js to verify request from wise.com. First time it works. But after some request, I got this:
![Screenshot 2024-10-10 at 14 28 47](https://github.com/user-attachments/assets/b0ef1493-57f5-4a86-9120-556c0cc7a568)

Is that wise is blocked our IP/ protocol or somethings?

**Comment by heeckhau** [comment]
Check your websocket proxy first
